[package]
name = "persway"
version = "0.3.0"
authors = ["John Axel Eriksson <john@insane.se>"]
edition = "2018"

[dependencies]
structopt = "0.3"
swayipc = { version = "2.4", features = ["async", "event_stream"] }
signal-hook = "0.1"